" General
"Disable Arrow Keys
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

set number	|" Show line numbers
set linebreak	|" Break lines at word (requires Wrap lines)
set showbreak=+++ |" Wrap-broken line prefix
set textwidth=100 |"Line wrap (number of cols)
set showmatch |"Highlight matching brace
set visualbell |"Use visual bell (no beeping)

set hlsearch |"Highlight all search results
set smartcase |"Enable smart-case search
set ignorecase |"Always case-insensitive
set incsearch |"Searches for strings incrementally

set autoindent |"Auto-indent new lines
set shiftwidth=2 |"Number of auto-indent spaces
set smartindent |"Enable smart-indent
set smarttab |"Enable smart-tabs
set softtabstop=2 |"Number of spaces per Tab

" Advanced
set ruler |"Show row and column ruler information
set undolevels=1000 |"Number of undo levels
set backspace=indent,eol,start	|" Backspace behaviour

" Generated by VimConfig.com

"Plugin modification-------------------------------------

"--------------------------vim-plug section -----------------------------
"Getting Started Video Tutorial: https://www.youtube.com/watch?v=nDv9iPv_8R4
call plug#begin('~/.vim/plugged')
  Plug 'junegunn/vim-easy-align'
  Plug 'sheerun/vim-polyglot'
  Plug 'tpope/vim-surround'
  Plug 'jiangmiao/auto-pairs'
  Plug 'vim-airline/vim-airline'
  Plug 'yggdroot/indentline'
  Plug 'airblade/vim-gitgutter'
  Plug 'editorconfig/editorconfig-vim'
  Plug 'luochen1990/rainbow'
  Plug 'ryanoasis/vim-devicons'
  Plug 'tpope/vim-fugitive' |"required in order to show git branch on vim-airline
  Plug 'ntpeters/vim-better-whitespace'
" Initialize plugin system
call plug#end()
